<?php

namespace DevTool\LaravelDevTool;

use DevTool\LaravelDevTool\Console\GenerateOpenApiCommand;
use DevTool\LaravelDevTool\Console\RegisterOpenApiResponseCommand;
use DevTool\LaravelDevTool\Console\UploadOpenApiToSoApiCommand;
use Illuminate\Support\ServiceProvider;
use DevTool\LaravelDevTool\Console\ModelAnnotationHelperCommand;
use L5Swagger\Console\GenerateDocsCommand;

class DevToolServiceProvider extends ServiceProvider
{

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $configPath = __DIR__ . '/../config/dev-tool.php';
            $this->publishes([
                $configPath => config_path('dev-tool.php'),
            ], 'dev-tool-config');
        }
    }

    public function register()
    {
        $this->registerCommands();
        $this->loadRoutesFrom(__DIR__ . '/routes.php');
    }

    protected function registerCommands()
    {
        $this->commands([
            ModelAnnotationHelperCommand::class,
            GenerateOpenApiCommand::class,
            UploadOpenApiToSoApiCommand::class,
            RegisterOpenApiResponseCommand::class,
        ]);
    }

    public function provides()
    {
        return parent::provides(); // TODO: Change the autogenerated stub
    }
}